default:
  APP_NAME: biteproject

  logs:
    LEVEL: info
    FILE: /tmp/lol.log

  fastapi:
    DEBUG: true
    API_PREFIX: /api

  database:
    URL: postgresql://pypis:somepassword@localhost:5432/pypis
    MAX_CONNECTIONS_COUNT: 10
    MIN_CONNECTIONS_COUNT: 10

  pypi_proxy:
    TIMEOUT: 10

  packages:
    BASE_DIRECTORY: /tmp/pkgs
    MAX_PACKAGES_VERSION_CACHE: 3

development:
  mdr: LOG_LEVEq<sd

testing:
  APP_NAME: testing-app
  LOG_LEVEL: debug
